# mosquitto.conf — broker MQTT casa inteligente (sin auth, solo uso interno)

listener 1883
allow_anonymous true

listener 9001
protocol websockets
allow_anonymous true

# Logging
log_type error
log_type warning
log_type information
log_dest stdout

persistence true
persistence_location /mosquitto/data/
